#!/bin/sh
#
# Taken from http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
#
# You need to configure vim to load .git/tags (or install Fugitive.vim).
#
mkdir .git/tags_lock 2>/dev/null || exit 0
trap "rmdir .git/tags_lock; rm -f .git/tags.$$" EXIT

if [[ -f Rakefile || -f Gemfile ]]; then
  $HOME/bin/ctags-ruby
else
  LANGS="-sql,-cobol"
  ctags --tag-relative -R -f .git/tags.$$ --exclude=.git "--languages=$LANGS" && \
    mv .git/tags.$$ .git/tags
fi
