#!/bin/sh
#
# Taken from http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
#
# You need to configure vim to load .git/tags (or install Fugitive.vim).
#
LANGS="-sql,-cobol"

mkdir .git/tags_lock 2>/dev/null || exit 0
trap "rmdir .git/tags_lock; rm -f .git/tags.$$" EXIT

# general purpose ctags
#ctags --tag-relative -R -f .git/tags.$$ --exclude=.git "--languages=$LANGS"

# ruby-only tags
ripper-tags --recurse --only-rb --vim --ignore-errors . > .git/tags.$$

mv .git/tags.$$ .git/tags
